### ISSUE TITLE
Invalid project error

### ISSUE THREAD

**Issue by mnaielksu1** [sneheshs/feva#6]
I am trying to create new project on FEVA to get started with a sample data. I see Invalid Project error on localhost html page, and then I found in the \static\data folder a folder for the project that I was trying to create that includes also 4 files (2 .avi files, 1 .gif file, 1.dat file) . I can not see the video in the annotation tool to start annotating. The system is Ubuntu 20.04 and I use python 3.5.2 under a conda environment, and the browser is chrome.

**Comment by sneheshs** [comment]
Thanks for the details. Please convert the video into MP4 and try again. AVI is not a supported format.

**Comment by mnaielksu1** [comment]
> Thanks for the details. Please convert the video into MP4 and try again. AVI is not a supported format.

Thanks a lot for the quick reply. Wonderful, I can see the page working now.
